global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["app:8000"]

  - job_name: "anomaly-detector"
    static_configs:
      - targets: ["anomaly-detector:8001"]
