version: "3.9"

services:
  app:
    build: ./services/app
    container_name: signalguard-app
    ports:
      - "8000:8000"
    environment:
      - ANOMALY_SERVICE_URL=http://anomaly-detector:8001
    depends_on:
      - prometheus
      - anomaly-detector

  anomaly-detector:
    build: ./services/anomaly-detector
    container_name: signalguard-anomaly
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    ports:
      - "8001:8001"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: signalguard-prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: signalguard-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
